In [1]:
import numpy as np

In [2]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [3]:
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [6]:
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [8]:
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
