In [1]:
import numpy as np

In [2]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [3]:
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [6]:
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [8]:
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [10]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [11]:
x.T

array([1, 2, 3])

In [13]:
x = np.array([[1, 2, 3]])

In [14]:
x

array([[1, 2, 3]])

In [20]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]   
])

In [21]:
print(X)

[[2 3 4]
 [1 2 3]]


In [22]:
X.shape

(2, 3)

In [23]:
row, col = X.shape

In [24]:
row

2

In [25]:
col

3

In [26]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--
