In [1]:
import numpy as np

In [2]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [3]:
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [4]:
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [5]:
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [7]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [8]:
x.T

array([1, 2, 3])

In [9]:
x = np.array([[1, 2, 3]])

In [10]:
x

array([[1, 2, 3]])

In [11]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]   
])

In [21]:
print(X)

[[2 3 4]
 [1 2 3]]


In [12]:
X.shape

(2, 3)

In [13]:
row, col = X.shape

In [14]:
row

2

In [15]:
col

3

In [16]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


In [17]:
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [18]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


In [19]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [20]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [21]:
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [22]:
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [23]:
import sklearn

In [24]:
from sklearn.linear_model import LinearRegression

In [30]:
#model = LinearRegression()
model = LinearRegression(fit_intercept=False)

In [31]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [32]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [33]:
model.intercept_

0.0

In [34]:
model.score(X, y)

0.6923076923076924

In [35]:
x = np.array([[1, 2, 3]])

In [37]:
y_pred = model.predict(x)
y_pred

array([[3.]])